"""remove role column from system_user

Revision ID: 4b3e86f22a0d
Revises: 68d47e37824a
Create Date: 2025-04-25 20:38:22.413297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3e86f22a0d'
down_revision = '68d47e37824a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
