"""Initial migration

Revision ID: 68d47e37824a
Revises: 
Create Date: 2025-04-25 20:31:58.182947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d47e37824a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_client_created_by_system_user', 'system_user', ['created_by'], ['id'])

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_enrollment_created_by_system_user', 'system_user', ['created_by'], ['id'])

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_program_created_by_system_user', 'system_user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_constraint('fk_program_created_by_system_user', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enrollment_created_by_system_user', type_='foreignkey')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_created_by_system_user', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
