"""add duration column to program

Revision ID: a57ae0f6fec7
Revises: 4b3e86f22a0d
Create Date: 2024-04-25 21:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57ae0f6fec7'
down_revision = '4b3e86f22a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('duration')
    # ### end Alembic commands ###
